### ISSUE TITLE
Apheleia conflicts with undo-tree-auto-save-history

### ISSUE THREAD

**Issue by sirn** [raxod502/apheleia#10]
When `undo-tree-auto-save-history` set to `t` and `apheleia-global-mode` is on, `apheleia` and `undo-tree` will go into a save buffer race causing the buffer to never be saved. 

------

### Steps to reproduce:

1. Enable `global-undo-tree-mode` and `apheleia-global-mode` 
2. Set `undo-tree-auto-save-history` to `t` 
3. Visit a file with apheleia autoformatting (e.g. `test.py`)
4. Type something and save a file (C-x C-s)

### Expected behavior:

The is saved and formatted

### Actual behavior:

The file is formatted, but become modified once again and cannot be saved unless I disable apheleia or undo-tree (or `C-u 0 C-x C-s` in case radian's hook)  

------

Reduced `init.el`:

```elisp
(setq user-init-file (or load-file-name (buffer-file-name)))
(setq user-emacs-directory (file-name-directory user-init-file))

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package '(apheleia :host github :repo "raxod502/apheleia"))
(straight-use-package 'undo-tree)

(require 'apheleia)
(require 'undo-tree)

(apheleia-global-mode +1)
(global-undo-tree-mode +1)

(setq undo-tree-auto-save-history t)
```

(I run this reduced `init.el` with: `/usr/bin/emacs -nw -q --load "/path/to/init.el"`)

------

Not sure whose bug this might be, please let me know if it's more appropriate to report to undo-tree instead (and sorry for the noise in such case). As always, HUGE thank you for straight.el, apheleia and radian :heart:

**Comment by raxod502** [comment]
Thanks for the lovely report. It was very easy to read. And it never occurred to me to set `user-emacs-directory` in an alternate init-file to avoid needing a hack in my `~/.emacs.d/init.el` to load it.

**Comment by sirn** [comment]
I just pull the commit 8112041d7e5f44587faff136d6ce52b9b1cea2eb and tested with both reduced init.el and my dotfiles and seems like the issue is fixed. The buffer now get updated properly without getting flagged as modified. Thank you!
