### ISSUE TITLE
How can I change line length settings for the black formatter?

### ISSUE THREAD

**Issue by mrbig033** [raxod502/apheleia#14]
Thank you for the awesome package. This is the only formatted that doesn't open all my folded code when I run it in the buffer.

I like to use `black`with the traditional line length. With blacken, I do this: `(setq blacken-line-length 79)`. I tried editing `apheleia-formatters`, but after many attempts I wasn't able to get the syntax right.

**Comment by raxod502** [comment]
```elisp
(setf (alist-get 'black apheleia-formatters) '("black" "-l" "79" "-"))
```

(untested)?

**Comment by mrbig033** [comment]
That worked fine thank you very much. A note in the README on how to add those options might save trouble in the future. Cheers!

**Comment by raxod502** [comment]
Done.
