### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by leungbk** [raxod502/apheleia#16]
It would be nice if this were hosted on MELPA.

**Comment by raxod502** [comment]
Would you like to submit a pull request adding it?

**Comment by PrimaryCanary** [comment]
I would like to. Would you like me to wait until my contributions are closer to completion?

**Comment by raxod502** [comment]
No need to. The package can be added as soon as anybody makes a pull request.

**Comment by afrepues** [comment]
@raxod502 @PrimaryCanary are you still interested in this? what would you recommend as next steps?

**Comment by raxod502** [comment]
Here's what `package-lint` reports:

```
3 issues found:

82:8: warning: Closing parens should not be wrapped onto new lines.
664:0: warning: Private functions generally should not be autoloaded.
693:2: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'apheleia"), to support the customization variable of the same name.
```

I fixed the first issue. The second two are, in my opinion, not actually bugs, and the current code should not be changed. I consider them a bug in `package-lint`, prior discussion at https://github.com/melpa/melpa/pull/6774#issuecomment-609049787.

**Comment by afrepues** [comment]
@raxod502 The package is now available in MELPA, this issue can be closed.
