### ISSUE TITLE
Infinite symlink lookup recursion when using apheleia--format-after-save

### ISSUE THREAD

**Issue by terlar** [raxod502/apheleia#18]
If I have configured:
`(setq vc-follow-symlinks t)` and are visiting a file under version control and then edit this file and then save with `apheleia-mode` enabled it enters some kind of infinite symlink follow recursion.

I will see output like this (and it will continue until I press C-g, at which point I get thrown out from the previous buffer which was formatted successfully):
```
Followed link to /dev/shm/buffer-content-ui2Z3V
Followed link to /dev/shm/buffer-content-BIEWUp
Followed link to /dev/shm/buffer-content-ORmfZq
Followed link to /dev/shm/buffer-content-MSk9TR
Followed link to /dev/shm/buffer-content-MG1VLT
Followed link to /dev/shm/buffer-content-Hhjuxl
Followed link to /dev/shm/buffer-content-gdLxGo
Followed link to /dev/shm/buffer-content-QsdyEP
Followed link to /dev/shm/buffer-content-sFHU8R
Followed link to /dev/shm/buffer-content-vJWO3i
Followed link to /dev/shm/buffer-content-CPrtWo
Followed link to /dev/shm/buffer-content-yJBDBX
Followed link to /dev/shm/buffer-content-4nU2f1
Followed link to /dev/shm/buffer-content-jTkcmA
Followed link to /dev/shm/buffer-content-Mfbp9E
Followed link to /dev/shm/buffer-content-utF0ud
Followed link to /dev/shm/buffer-content-uCuUYi
Followed link to /dev/shm/buffer-content-RyZ7kO
Followed link to /dev/shm/buffer-content-yhqNTT
Followed link to /dev/shm/buffer-content-CBcCwo
Followed link to /dev/shm/buffer-content-itulmu
Followed link to /dev/shm/buffer-content-R4XDZY
Followed link to /dev/shm/buffer-content-kDbsj5
Followed link to /dev/shm/buffer-content-Cx1QPB
Followed link to /dev/shm/buffer-content-MxSF8J
Followed link to /dev/shm/buffer-content-H3tsTg
Followed link to /dev/shm/buffer-content-MGU45o
Followed link to /dev/shm/buffer-content-AiPN6U
Followed link to /dev/shm/buffer-content-idLNM2
Followed link to /dev/shm/buffer-content-9vFLOy
Followed link to /dev/shm/buffer-content-knWU5C
Followed link to /dev/shm/buffer-content-07XDc6
Followed link to /dev/shm/buffer-content-stIYId
```

If I don't enable `vc-follow-symlinks` it won't happen, but then instead I will end up in a buffer with the correct file-name, but which is not actually the file in the project and it will lose the VC status information.

I am not sure this error stems from apheleia, but it might be a regression introduced in the latest Emacs HEAD, I am currently running:
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.16.0)
on commit https://github.com/emacs-mirror/emacs/tree/ffb89ed5f07491e33fc79d8b4be49d9deba2ad4a

It does not seem to happen when I trigger `apheleia-format-buffer` manually.

Any ideas what can be wrong and if this is something that needs to be reported to Emacs itself, which I suspect might be the case.

Thank you for your assistance.

**Comment by raxod502** [comment]
Yes, that looks like a bug. I am not sure what could be wrong, without installing the latest Emacs and doing a more detailed analysis. See also https://github.com/raxod502/apheleia/pull/12 which may be the same problem. I was unable to reproduce that problem.

**Comment by terlar** [comment]
Ah! I am using, diff-hl with flydiff mode, so it is probably the same issue. The weird thing is that I have been using both these together for at least a year without this issue. So I still suspect a regression in Emacs, I will try out an older version to see if I can reproduce it. Any way to provide some debugging info for this?

**Comment by raxod502** [comment]
Unfortunately, I do not have any hypotheses. Someone who can reproduce the problem needs to put in debugging statements to the relevant Apheleia functions to see who is calling what, and the values of the relevant hooks when that happens.

**Comment by raxod502** [comment]
I'd like to look into this at long last. Can you verify if the issue is still occurring, and if so, what your Emacs version is? I have been unable to thus far with `GNU Emacs 28.0.50 (build 17, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-09-06`.

The problem seems to center on this function, since it's the only place in Emacs source code where I can find a reference to temporary files named `buffer-content-`:

```elisp
(defun diff-file-local-copy (file-or-buf)
  "Like `file-local-copy' but also supports a buffer as the argument.
When FILE-OR-BUF is a buffer, return the filename of a local
temporary file with the buffer's contents."
  (if (bufferp file-or-buf)
      (with-current-buffer file-or-buf
        (let ((tempfile (make-temp-file "buffer-content-")))
          (write-region nil nil tempfile nil 'nomessage)
          tempfile))
    (file-local-copy file-or-buf)))
```

**Comment by terlar** [comment]
Hmm, I enabled apheleia again and didn't manage to reproduce it. So either it is something that is fixed in Emacs or something that has been fixed on the `dired-hl` side. I will switch to apheleia as my daily driver to see if I run into this again.

**Comment by raxod502** [comment]
Awesome, let me know if it reproduces and I will reopen.
