### ISSUE TITLE
Fails for buffers greater than 2^16 characters

### ISSUE THREAD

**Issue by raxod502** [raxod502/apheleia#20]
Unfortunately, we get errors

```
Failed to run prettier: process aphelieia-prettier no longer connected to pipe; closed it
Failed to run prettier: exit status 256 (see hidden buffer *apheleia-prettier-stderr*)
```

when a buffer's size exceeds 65,536 characters. I am not aware of any workaround other than disabling Apheleia. Note that the error is unrelated to any particular code formatter, since it reproduces with `cat`.

**Comment by raxod502** [comment]
This does not reproduce on `GNU Emacs 28.0.50 (build 17, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-09-06`, so documenting as a known issue and closing.

**Comment by jarreds** [comment]
@raxod502 I'm seeing the 65,536 limit here again on a new version of emacs.

```
GNU Emacs 30.2 (build 1, aarch64-apple-darwin25.0.0, NS appkit-2685.10 Version 26.0.1 (Build 25A362)) of 2026-01-12
```

You mentioned you could repro w/ cat. What was your incantation to make that happen? Trying to figure out if there is a setting I can tweak to resolve this.

**Comment by jarreds** [comment]
One workaround of note: switching to `inplace` and passing flags for the formatter to write in place gets around the limit.

```diff
   apheleia-global-mode
   :config
-  (setf (alist-get 'gofumpt apheleia-formatters) '("gofumpt" filepath)
-        (alist-get 'goimports apheleia-formatters) '("goimports" filepath)
+  (setf (alist-get 'gofumpt apheleia-formatters) '("gofumpt" "-w" inplace)
+        (alist-get 'goimports apheleia-formatters) '("goimports" "-w" "-local" "github.com/my/repo" inplace)
         (alist-get 'go-ts-mode apheleia-mode-alist) '(gofumpt goimports)
         (alist-get 'prettier-json apheleia-formatters) '("prettierd" "--stdin-filepath" filepath))
```

**Comment by raxod502** [comment]
> You mentioned you could repro w/ cat

Just registering a custom formatter where the command is `cat` and nothing else.
