### ISSUE TITLE
Is there a way to add a non stdin/stdout formatter?

### ISSUE THREAD

**Issue by systemctl603** [raxod502/apheleia#23]
Hi,

So I tried to get `flutter format` working in apheleia. The problem is, this command
directly writes to the file. AFAIK, there is no option to write to stdout.

My question is, is there a way to add a formatter that only writes directly
to the file?

**Comment by raxod502** [comment]
Is it okay if the file is copied to a temporary directory before the formatter is run on it?

**Comment by systemctl603** [comment]
Yeah, that seems fine.

**Comment by raxod502** [comment]
I pushed to a temporary branch (linked above) my work-in-progress implementation, which should support the interface necessary for this type of formatter. Unfortunately, the implementation still has a bug that needs to be fixed for it to work properly. At the moment I don't have the time to work further on it, but I figured I would publish the code so somebody else can take a look if they are so inclined.

**Comment by raxod502** [comment]
Implemented with the latest commit.
