### ISSUE TITLE
Automated formatter testing and CI

### ISSUE THREAD

**Issue by PrimaryCanary** [raxod502/apheleia#25]
Do you want me to set up a testing framework for supported formatters? I'm imagining a system similar to [flycheck's](https://github.com/flycheck/docker-tools) where a Docker container installs all checkers and runs a test suite against them.

We could discuss details if you think this is something worth working on.

**Comment by raxod502** [comment]
Sure! I certainly will never object to someone offering to write tests ;) 

What Flycheck has looks like a great setup, and I would be happy to offer further thoughts and advice. I am fairly familiar with the challenges of building large Docker images, having written https://github.com/raxod502/riju which constructs about a 25GB image containing 226 programming languages and associated tooling.

**Comment by raxod502** [comment]
Implemented in #72.
