### ISSUE TITLE
Trying to add a new formatter for eslint_d

### ISSUE THREAD

**Issue by terlar** [raxod502/apheleia#3]
I am trying to add a new formatter for `eslint_d` and looking at the examples for `black` and `prettier` I can't understand why it doesn't work.

I have done some step through debugging and see that it creates the process properly and sends the buffer on stdin, only thing I noted there was that the buffer seemed to include faces and font-lock styling etc.

Not sure if this is causing the issue. After it is executed I receive nothing, no output to indicate error or success. I guess if it succeded it would run the diff and apply function next.

The command I have configured is:
```
(cl-pushnew '(eslint . (npx "eslint_d" "--fix-to-stdout" "--stdin" "--stdin-filename" file)) apheleia-formatters :test #'equal)
```

**Comment by raxod502** [comment]
Thanks for your report! I had some difficulty figuring out how to install and configure this tool, however, so I wasn't able to reproduce the problem. Would you mind providing an example repository (or just the content of its files) which can be used to show that running the command manually works, but running it with Apheleia doesn't?

**Comment by terlar** [comment]
Thank you for your input, I remember myself when trying to install eslint, it is quite of a mess, I have prepared a repo with code where it should be ready to run with the following steps (assuming npm/node is installed):

1. `cd app/typescript`
2. `npm install`
3. `npx eslint_d --cache --fix-to-stdout --stdin --stdin-filename app-with-lint-errors.ts < app-with-lint-errors.ts`

The repo is the following: https://github.com/terlar/sam-playground

Let me know if anything is unclear.

Then running Apheleia in the same repo as described above, doesn't work. I can also mention that I run `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8)` which might affect things.

**Comment by raxod502** [comment]
I cannot reproduce this. I successfully ran the commands you provided, redirecting the output to `app-with-lint-errors-formatted.ts`. Then I opened `app-with-lint-errors.ts` in Emacs, ran the `cl-pushnew` command, and invoked `C-u M-x apheleia-format-buffer`, selecting `eslint` from the list. That formatted the buffer, producing the same result (verified via `diff -s app-with*`) as the manual command.

I am running Emacs HEAD on Manjaro Linux. Any ideas?

**Comment by terlar** [comment]
Hmm, I tried again with your provided steps and it works and was a bit surprised. What I usually had issues with was the formatting triggered on save. Which I got working now, but I see very inconsistent behaviour when adding extra white-space that needs to be trimmed, but no issues when just formatting needs to be changed.

I am pretty sure this is an issue with my end, I am currently using ws-butler, and I believe the way these commands run together conflict a bit. I think ws-butler uses a similar aproach to run changes on a separate buffer and apply them later.

So this was not an issue with `eslint_d` per se, I will close this issue for now and potentially open a new one with correct description if I find out the issue.

Hopefully it would be possible to run together with ws-butler in some way.

**Comment by SalTor** [comment]
@terlar were you ever able to get eslint_d set up as a formatter with apheleia? I've been using the eslintd-fix package in addition to apheleia and would like to use just apheleia if you got it to work

**Comment by gkazl** [comment]
In case anyone is still looking:

```elisp
(use-package! apheleia
  :config
  (push
   '(eslint
     . ("apheleia-npx" "eslint_d" "--fix-to-stdout" "--stdin" "--stdin-filename" file)) apheleia-formatters)

  (setf (alist-get 'typescript-mode apheleia-mode-alist)
        '(eslint)))
```
