### ISSUE TITLE
After post-save auto-formatting, buffer visits a Flycheck temp file

### ISSUE THREAD

**Issue by leungbk** [raxod502/apheleia#35]
``` elisp
(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(setq debug-on-error t)

(use-package apheleia
  :straight (:repo "raxod502/apheleia" :host github)
  :demand t
  :config
  (apheleia-global-mode 1))

(use-package flycheck
  :demand t
  :config
  (global-flycheck-mode 1))
```

Repro:

1. `emacs -q -l above-init.el`. The Python-formatter `black` should also be installed.
2. `C-x C-f hello.py`
3. Write

``` python
def hi():


    return 42
```

and then save the file, allowing Apheleia to clean up the extra whitespace.

4. `M-: (buffer-file-name)`. The output is `/tmp/flycheckpqHf80/hello.py`, instead of the expected `/home/alice/hello.py`.

Funny enough, `M-x apheleia-format-buffer` on the above whitespace-heavy file does not permanently visit the temp file in this manner.  However, manually saving the formatted buffer (which does not trigger an auto-format of the file, since it was just formatted manually) does cause the temp file to be visited.

I can reproduce this on both Emacs 27 (on macOS, installed via Nix) and Emacs 28 (on NixOS).

**Comment by raxod502** [comment]
Yep, can confirm this definitely happens.

**Comment by raxod502** [comment]
I suspect it is due to interference between `flycheck-handle-save` and `apheleia--format-after-save`, both of which are active on `after-save-hook`.

**Comment by shackra** [comment]
an annoying bug, this happens to me on JSON files

**Comment by raxod502** [comment]
With the latest commit, I am unable to reproduce this anymore. @leungbk or @shackra, can you check whether you observe the same on your end?

**Comment by leungbk** [comment]
Looks like you fixed it. Thanks!
