### ISSUE TITLE
Don't change default-directory?

### ISSUE THREAD

**Issue by apeschar** [raxod502/apheleia#36]
What's the reason that default-directory is set to the project root instead of left unchanged as the directory that the file is in?  If the project contains different formatter configs in different subfolders, the wrong one (or none) will get used.

In my `init.el`, I added:

~~~
(defun apheleia--project-root () default-directory)
~~~

But I'm wondering whether this functionality is not better removed altogether? Most if not all formatters should automatically find the right config in parent folders.

**Comment by lassik** [comment]
Running most formatters in the file's director (not the project's) is the right thing.

Only a handful of formatters require a hack to run from the project root directory. Format-all's code shows which ones.

**Comment by apeschar** [comment]
It looks like none of the formatters for which format-all changes default-directory are supported by prettier.  So until that is the case, I believe this behavior can safely be removed.

I will submit a PR.

**Comment by raxod502** [comment]
Reverted this change in https://github.com/raxod502/apheleia/commit/87115f5cda2a6c0653fc0ac69bbbc7d39a253f11.

**Comment by apeschar** [comment]
Let's continue the discussion on this in #30.
