### ISSUE TITLE
apheleia--write-file-silently ignores visit in write-region

### ISSUE THREAD

**Issue by haji-ali** [raxod502/apheleia#39]
This is a bit of a weird issue, I admit, but after a long debugging session of my Radian config I finally tracked it down to apheleia.

I am using `undo-fu-session` which has a `before-save-hook` to save the undo data. In this hook, there's code like this:
```elisp
(with-auto-compression-mode
        (with-temp-buffer
           ...
          (write-region nil nil undo-file nil 0)
          t))
```
where the function `write-region` is called on a temporary buffer. Note that `0` is passed to `visit` of `write-region`. The buffer content should be written to a file but the temporary buffer should not visit the file. I was surprised to see that the buffer was in fact visiting the file in `undo-file` causing annoying dialogue boxes of "buffer changed.. save anyways?" everytime auto-save runs and if I select Yes to save, the undo file is overwritten!

I found out that the reason is `apheleia--write-file-silently` where the function `write-region` is bound to a lambda function that ignores the `visit` argument and instead always passes `t` in its place causing the file to be always visited (even if the buffer is temporary). 

I can see that in the commit 8112041d7e5f445 `visit` is always set to `t` instead of `0` to fix an issue with `undo-tree`, but I am wondering why the `visit` argument is ignored at all? It seems to me that ignoring an argument of a such a basic function is a radical measure.

**Comment by raxod502** [comment]
Yeah, I think that's a bug. Thanks for the good analysis. That code is left over from a previous, buggy version of `apheleia--write-file-silently`. I've made an adjustment that should fix these issues once and for all.

**Comment by raxod502** [comment]
Let me know if this fixes your problem.

**Comment by haji-ali** [comment]
Yep, this fixes the issue. I had this fixed implemented locally, but wasn't sure if it would affect apheleia in some other use-case.
