### ISSUE TITLE
apheleia messes with `*jka-compr-wr-temp*` buffer somehow

### ISSUE THREAD

**Issue by shackra** [raxod502/apheleia#41]
I noticed that after editing a TSX file in Emacs and saving, a buffer called `*jka-compr-wr-temp*` is created and is linked to a file located in [`undo-fu-session-directory`](https://github.com/emacsmirror/undo-fu-session/blob/master/undo-fu-session.el#L66) and when I try and close Emacs, naturally the editor tells me if I want to save that buffer/file before quitting which is annoying:

```
Save file /home/jorge/.emacs.d/.local/cache/undo-fu-session/60bb5b95f70b5c8292b03b6db987f789ce8c7c76.zst (buffer  *jka-compr-wr-temp*)? (y, n, !, ., q, C-r, C-f, d or C-h)
```

I know this is somehow related to apheleia because if I disable it in my configuration and restart Emacs, try to reproduce and then check the buffer list, the buffer `*jka-compr-wr-temp*` is not linked to any file:

![image](https://user-images.githubusercontent.com/1055216/123358201-4cdea580-d528-11eb-8401-e73e5a02266d.png)

this happens with the latest commit f865c165dac606187a66b2b25a57d5099b452120

[My config](https://gitlab.com/shackra/emacs) is based on Doom Emacs, but Apheleia is not provided by Doom (I added it myself)

**Comment by raxod502** [comment]
Likely the same root cause as https://github.com/raxod502/apheleia/issues/35, but we can track it separately because we don't know that for sure.

**Comment by shackra** [comment]
FYI: this is where I hold Apheleia as a module for Doom https://github.com/shackra/emacs/tree/master/modules/editor/reformat

**Comment by raxod502** [comment]
Same as https://github.com/raxod502/apheleia/issues/35#issuecomment-1005380134, can you let me know if the issue is still occurring? If so I can investigate further.

**Comment by shackra** [comment]
no, is not happening anymore

**Comment by raxod502** [comment]
Awesome, thank you!
