### ISSUE TITLE
Error buffers are hidden, which makes it hard to see the problem

### ISSUE THREAD

**Issue by daanturo** [raxod502/apheleia#46]
When formatting fails, we have to:
1. Navigate to \*Messages\*
2. Search for "Failed to run ...: exit status ... (see hidden buffer *apheleia-...-stderr*)"
2. Copy the " *apheleia-...-stderr" buffer name, including the the initial space
3. Type `M-S-; (switch-to-buffer " *apheleia ... stderr") RET`

Should there be a less painful way?

**Comment by raxod502** [comment]
Typically if you type a leading space in `C-x b`, then tab completion will now show you hidden buffers. That said, the process is still unergonomic, and I'd like to have something better. Perhaps, for example, it would make sense to have a command to show the error buffer for the formatter associated with the current file.

**Comment by raxod502** [comment]
With the above commit and some previous ones, stdout and stderr buffers are replaced with log buffers that contain persistent information about multiple runs of a formatter, and include additional metadata. Log buffers are not hidden by default, although the previous behavior can be restored by configuring `apheleia-hide-log-buffers`. Furthermore, there is a new interactive command `apheleia-goto-error` which can be used to jump to the error that was most recently reported.
