### ISSUE TITLE
Processes that fail stick around

### ISSUE THREAD

**Issue by axelf4** [raxod502/apheleia#47]
From what I can tell, formatter processes that fail never get freed. I do not have `clang-format` installed so when saving a C file I the message

    Failed to run clang-format: Searching for program: No such file or directory, clang-format

is echoed, which is fine. However, looking at the output of `M-x list-processes` it seems that the process list is getting clogged up:
```
Process [v]     PID     Status  Buffer                    TTY          Thread       Command
apheleia-cla... --      open     *apheleia-clang-forma... --           Main
apheleia-cla... --      open     *apheleia-clang-forma... --           Main
...
apheleia-cla... --      open     *apheleia-clang-forma... --           Main
server          --      listen  --                        --           Main         (network server on /run/user/1000/emacs/server)
server <1>      --      open    --                        --           Main         (network connection to t:/run/user/1000/emacs/server)
```
I do believe this is what caused my Emacs instance to start failing with "Too many open files" until killed.

For formatters I do have installed this is not an issue.

I am on commit 8e022c67fea4248f831c678b31c19646cbcbbf6f.

**Comment by raxod502** [comment]
Ah, those processes are probably the stderr pipes that Emacs opens in order to forward stderr separately from stdout. It could be an Emacs bug or a bug in how we are using the process manipulation API. Either way, it's probably possible for us to work around it by explicitly killing the stderr process if the main one fails.

**Comment by raxod502** [comment]
Should be fixed with the above commit.
