### ISSUE TITLE
Better handling for non-file buffers

### ISSUE THREAD

**Issue by mohkale** [raxod502/apheleia#52]
Atm apheleia has `filepath` and `file` command specifiers that're replaced with the value of the current buffers file. Quite a lot of the time I'm working with virtual files (such as by creating an org src-block for some c code) and apheliea will refuse to format that buffer (when called interactively through `apheleia-format-buffer`) because its been modified and it doesn't have a file-name. There should be a way to format buffers as well as files.

**Comment by mohkale** [comment]
I end up wanting this frequently enough to try and implement it now :smile:.

> I think what we could do is, check if buffer-file-name is nil.

Is there a reason we prefer the variable `buffer-file-name` over the function? Just curious. I didn't even know there was a variable until I worked on this code base.

> If it is, then when processing file or filepath we can pretend like input was used instead. 

I think a reasonable compromise would be to use the `(buffer-name)` in this case. That at least gives some level of configurability to users for multi-file-type formatters like clang-format which seems to take the file extension to decide how to format something (frankly kind of apalling there's no way to specify the format distinct from the filename).

**Comment by mohkale** [comment]
Thinking about this more it would be great if there was some way to hook apheleia-mode into indirect buffers like `separedit` (`edit-indirect.el`) or org source code blocks. Might be simple enough to do by parameterising `apheleia--format-after-save` and providing alternatives to `apheleia--write-file-silently` for these other buffer types.

**Comment by raxod502** [comment]
> Is there a reason we prefer the variable `buffer-file-name` over the function

No reason, I think they do exactly the same thing. I didn't know there was a function until just now!

> I think a reasonable compromise would be to use the `(buffer-name)`

That could work, as long as we do a reasonable job at translating the buffer name (which could be something bizarre like, say, `*scratch*`) into an appropriate temp file name.

> Might be simple enough to do by parameterising `apheleia--format-after-save`

Sure, we could maybe introduce a buffer-local user option that could be customized with a different way of performing the "save" operation instead of `apheleia--write-file-silently`.

**Comment by mohkale** [comment]
> That could work, as long as we do a reasonable job at translating the buffer name (which could be something bizarre like, say, *scratch*) into an appropriate temp file name.

We're only using the buffer-file-names extension when creating a temp file, so I don't think there's an issue there. On the other hand I suppose there's a chance someone could have a buffer like `*foo.bar*` so it might be worth removing weird characters (at least for windows). 

> Sure, we could maybe introduce a buffer-local user option that could be customized with a different way of performing the "save" operation instead of apheleia--write-file-silently.

Looked into it, might be a little too ambitious for this issue. The indirect-buffer might not exist by the time the formatter is done, instead will want to format a region in the original buffer but formatting regions is a separate issue to work on.

**Comment by raxod502** [comment]
Fair point on both, sounds good!
