### ISSUE TITLE
Formatting a buffer changes the mode

### ISSUE THREAD

**Issue by Lokdex** [raxod502/apheleia#58]
Using the format on save, or manual formatting of the file causes the mode to revert to whatever is the default. i.e. if you open a buffer and set it to web-mode, after the formatting is done it returns to fundamental mode.

Also, it has a bug relating to php-mode. If php-mode is active, Apheleia attempts to format it using clang-formatter, which then obviously causes an error, in my case, it says clang-formatter cannot be found.

**Comment by raxod502** [comment]
Ah, well, for php-mode it looks like it is derived from c-mode. My first question would be why is that the case, which would be a question for the php-mode author(s). But, there is no reason we cannot work around the issue in Apheleia. The above commit should fix that.

**Comment by raxod502** [comment]
For your main comment, yeah, that is a known issue and it bothers me as well. I think we can adjust the way buffers are saved by Apheleia to fix the issue, though I don't have the bandwidth to investigate myself just now.

**Comment by raxod502** [comment]
Let me know if you are still experiencing this issue.

**Comment by Lokdex** [comment]
Nope, I just installed it again and it works as expected. Thanks!
