### ISSUE TITLE
Functional formatters (for use with lsp-mode/eglot)

### ISSUE THREAD

**Issue by mohkale** [raxod502/apheleia#62]
I've noticed apheleia atm doesn't support functional formatters, such as `pp-buffer`. 

I'd like to add support for using language servers (eglot, or lsp-mode) for formatting a buffer on save through apheleia so I'd like apheleia to support functional formatters. 

I'm interested in what your thoughts on this would be. Implementation wise it might be more convenient to clone the current buffer, or copy it and then run the formatter on the cloned buffer and continue with the changes we were already doing. This would also allow chaining with the existing formatter system. So we could say format with lsp-mode, then run python-isort, etc.

Interface wise I was thinking we just allow the cdr of an entry in `apheleia-formatters` to be a symbol, and if it is then its a function to call. Luckily atm their all lists, even gofmt.

**Comment by mohkale** [comment]
@raxod502 Ping.

**Comment by raxod502** [comment]
Sorry, sorry, left a comment on the PR. Thanks for taking this up!

**Comment by mohkale** [comment]
> Sorry, sorry, left a comment on the PR.

No problem, and I'm more than happy to contribute since I really value this project. :smile:.
