### ISSUE TITLE
ktfmt and other formatters which output nothing to stdout on success clobber buffer

### ISSUE THREAD

**Issue by elizagamedev** [raxod502/apheleia#66]
I don't particularly know why [ktfmt](https://github.com/facebookincubator/ktfmt) behaves in this way, but if stdin is already formatted properly, nothing will be printed to stdout, causing apheleia to delete the contents of the entire buffer. I see three ways to approach fixing this:

- Change apheleia to be able to handle cases like this. (ideal)
- Add an option to ktfmt to always print something to stdout. (semi-ideal)
- Write a wrapper script around ktfmt which always prints something. (not very ideal at all)

I'm going to be raising an issue on their tracker as well, since I feel like this behavior is unexpected and should probably have an option to disable it. That said, I do think there are probably other formatters that work like this somewhere out there and that apheleia should be able to handle them ideally. I wanted to raise this issue before implementing, since I wanted your feedback before creating a patch.

That all said: maybe we could just not touch the buffer at all if stdout is empty, and the return code is 0? I can't imagine a scenario in which an empty/entirely whitespace buffer would need special formatting at all (unless there's someone silly enough to have written a formatter for the [whitespace programming language](https://en.wikipedia.org/wiki/Whitespace_%28programming_language%29).

**Comment by raxod502** [comment]
Thanks for the good report. I agree with you about the available options. I think we should first inspect the potential of fixing this upstream. Maybe there's something I'm missing, but this behavior seems like obviously a bug and I can't think of any possible use case where it would be desired. I don't know how you would actually use the formatter in any other tooling. Format the file, direct the output to the formatted file... then manually check if the formatted file is empty, and if it is, copy the original? That seems bizarre.

Anyway, let me know how it goes upstream; if they can provide some kind of explanation why this behavior would actually make sense then I guess we can implement a workaround here as you suggested.

**Comment by raxod502** [comment]
Looks like this got resolved upstream! :rocket:
