### ISSUE TITLE
How can I apply diminish-mode to aphelei-mode?

### ISSUE THREAD

**Issue by avatar-lavventura** [raxod502/apheleia#79]
I am using [`diminish`][1] for major modes. But I was not able to apply it for `apheleia-mode`.

```lisp
(apheleia-global-mode +1)
(with-eval-after-load 'apheleia
(setf (alist-get 'isort apheleia-formatters)
      '("isort" "--stdout" "-"))
(setf (alist-get 'python-mode apheleia-mode-alist)
      '(isort black))
  )
(diminish 'apheleia-mode)
(diminish 'apheleia-global-mode)
```

I keep see following `Apheleia` at bottom line, how can I suppress it:

`Driver.py   ~/program/user Git:dev (home) [Py]  Top (15, 0)  Apheleia------------`

  [1]: https://github.com/myrjola/diminish.el

**Comment by phil-s** [comment]
https://emacs.stackexchange.com/questions/70367/how-can-i-apply-diminish-to-apheleia-mode

**Comment by phil-s** [comment]
I'm not sure the surprising autoload hack is worthwhile for the very small amount of init time it's saving, but that's just IMHO.

**Comment by avatar-lavventura** [comment]
Solved in here: https://emacs.stackexchange.com/a/70379/18414

**Comment by raxod502** [comment]
Sorry for the inconvenience. That solution is indeed my recommendation as well; you can see [I do the same in my configuration](https://github.com/raxod502/radian/blob/2d3a1f8c62ce4804bda94f26d7f70674bec941bf/emacs/radian.el#L2180-L2185).

**Comment by liebkne** [comment]
How can I translate the code snippet

```
(diminish 'apheleia-mode)
(apheleia-global-mode +1)
(with-eval-after-load 'apheleia
  (diminish 'apheleia-mode)
  ...
  )
```

 to `use-package`?

```
(use-package apheleia
  :diminish apheleia-mode
  :init
  (diminish 'apheleia-mode)

  :config
  (with-eval-after-load 'apheleia
    (diminish 'apheleia-mode)))
```

The above snippet does not work.

**Comment by raxod502** [comment]
It seems to be working for me. Can you file a new ticket with an example of how to reproduce the problem from a blank init.el?
