### ISSUE TITLE
Package name error in installation instructions

### ISSUE THREAD

**Issue by xcapaldi** [raxod502/apheleia#82]
In the Readme [installation section](https://github.com/raxod502/apheleia#installation) it is specified that:

`el-patch` is available on [MELPA](https://melpa.org/). It is easiest to install it using ...

I think this should be:

`apheleia` is available on [MELPA](https://melpa.org/). It is easiest to install it using ...

This seemed too trivial to be worth forking and opening a PR.

**Comment by raxod502** [comment]
Thanks. I seem to be very bad at getting this right, so thanks.
