### ISSUE TITLE
`apheleia-formatters` docstring outdated w.r.t. functional formatters

### ISSUE THREAD

**Issue by jinnovation** [raxod502/apheleia#86]
The `apheleia-formatters` docstring details as relates to formatters as Elisp functions is outdated and warrants updating.

#63 introduced the ability to set arbitrary Elisp functions as formatters in `apheleia-formatters`. #76 afterwards changed the expected signature from four positional arguments to key-value plist arguments. This change was called out in the [changelog](https://github.com/raxod502/apheleia/blob/master/CHANGELOG.md?plain=1#L8-L13), which is excellent, but the `apheleia-formatters` docstring's notes regarding functional formatters should be updated.

For reference, here's the [clause](https://github.com/raxod502/apheleia/blob/master/apheleia.el#L932-L939) in question:
> If the value is a function, the function will be called with four
arguments to format the current buffer: the original buffer that
was being formatted (use this to access any relevent local
variables or options that the formatter needs); a clone of the
original buffer (that may have been modified by another formatter
prior to being passed to the function); a callback that should be
called when formatting is finished; and another callback that
should be called when an error was raised during formatting.

**Comment by raxod502** [comment]
Thanks for noticing! Fixed in the above commit. cc @mohkale
